FROM node:10

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install browserify -g

COPY . .

# RUN  mkdir public/build

RUN browserify public/javascripts/listDevice.js --standalone listDevices > public/build/list.js

RUN browserify public/javascripts/addDevice.js --standalone addDevice > public/build/addDevice.js

RUN browserify public/javascripts/createTask.js --standalone performTask > public/build/task.js

RUN browserify public/javascripts/removeDevice.js --standalone remove > public/build/remove.js

RUN browserify public/utils/test.js --standalone testDeviceApi > public/build/test.js

RUN browserify public/javascripts/xterms.js > public/build/bundle.js

EXPOSE 3000

CMD ["npm", "start"]